apiVersion: v1
kind: ServiceAccount
metadata:
  name: rides-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rides-workflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rides-workflow
subjects:
  - kind: ServiceAccount
    name: rides-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rides-workflow
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - get
      - watch
