apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    app.kubernetes.io/name: hive-metastore-postgres
  name: hive-metastore-postgres
spec:
  databases:
    hivemetastore: hive-metastore-admin
  enableLogicalBackup: false
  numberOfInstances: 1
  postgresql:
    version: "13"
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 16Mi
  teamId: hive-metastore
  users:
    hive-metastore-admin:
      - superuser
      - createdb
  volume:
    size: 100Mi
