apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
stringData:
  # minio helm chart expects `root-*` keys in the secret,
  # duplicating it with conventional `access` and `secret` keys
  # TODO file a PR to helm chart to allow custom secret key names
  root-user: "argoworkflowshowcase"
  root-password: "argoworkflowshowcase"
  access-key: "argoworkflowshowcase"
  secret-key: "argoworkflowshowcase"
### TODO: replace with the CR below after integration with Vault is configured
#  apiVersion: external-secrets-operator.slamdev.net/v1alpha1
#  kind: ExternalSecret
#  metadata:
#    name: minio-credentials
#  spec:
#    backendName: vault
#    keys:
#      - kv/data/minio
