name: Test

on:
  - pull_request
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISABLE_IMAGE_CACHE: "false"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache images
        uses: actions/cache@v2
        if: env.DISABLE_IMAGE_CACHE == 'false'
        with:
          key: images
          path: .github/kind/images

      - name: Ensure cache dir exists
        if: env.DISABLE_IMAGE_CACHE == 'false'
        run: |
          mkdir -p .github/kind/images

      - name: Load docker images
        if: env.DISABLE_IMAGE_CACHE == 'false'
        run: |
          find .github/kind/images -name *.tar -exec docker load -i {} \;

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          name: aw-showcase
          config: .github/kind/cluster.yaml
          version: v0.11.1

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: 3.7.1

      - name: Setup Skaffold
        uses: volesen/setup-skaffold@v1.1
        with:
          version: v1.35.0

      - name: Load cluster apps images
        if: env.DISABLE_IMAGE_CACHE == 'false'
        # TODO remove filtering out of hardcoded external images
        run: |
          for i in $(docker images --format '{{.Repository}}:{{.Tag}}' | grep -v 'node:' | grep -v 'buildpack-deps:' | grep -v 'ubuntu:' | grep -v 'debian:' | grep -v 'alpine:') ; do
            kind load docker-image --name=aw-showcase "${i}"
          done

      - name: Deploy apps
        run: |
          make apply

      - name: Verify workflow
        run: |
          RETRIES=50
          while [ ${RETRIES} -gt 0 ]; do
            PHASE=$(kubectl get workflow -nshowcase rides-workflow -ojsonpath='{.status.phase}')
            if [ "${PHASE}" == "Succeeded" ]; then
              kubectl get workflow -nshowcase
              exit 0
            fi
            RETRIES=$((RETRIES - 1))
            echo "::notice::workflow is in ${PHASE} phase; rechecking in 10s; ${RETRIES} retries left"
            echo "::notice::list of showcase pods:"
            kubectl get pods -nshowcase
            sleep 10
          done
          kubectl get pods --all-namespaces
          exit 1

      - name: Export images
        if: env.DISABLE_IMAGE_CACHE == 'false'
        run: |
          IMAGES=$(docker exec aw-showcase-control-plane crictl images -o json | jq -r '.[] | .[] | .repoTags | .[]')
          IMAGES="${IMAGES} kindest/node:v1.21.1"
          for image in ${IMAGES}; do
            file_name=".github/kind/images/$(echo "${image}" | sed "s/\///g").tar"
            if [ -f "${file_name}" ]; then
              echo "found a saved ${image} image file: ${file_name}"
              continue
            fi
            echo "saving ${image} to ${file_name}"
            docker pull "${image}"
            docker save "${image}" -o "${file_name}"
          done
